import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playfair = Montserrat({
  subsets: ["latin"],
  variable: "--font-playfair"
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark">
      <body className={`${playfair.variable} font-playfair antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <div className="max-md:px-6 w-full max-w-3xl mx-auto">
            {children} 
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}